version: '3'

services:
  ## the following are all existing ones for diabetes dataset
  processrd:
    deploy:
      replicas: 1
    build: processrd
    environment:
      - TRAINR_D_ENDPOINT=http://trainrd:7770
    ports:
      - "8880:8880"

  trainrd:
    deploy:
      replicas: 1
    build: trainrd
    environment:
      - PREDICTR_D_ENDPOINT=http://predictrd:9990
    ports:
      - "7770:7770"
    volumes:
      - ./models:/app/models

  predictrd:
    deploy:
      replicas: 1
    build: predictrd
    ports:
      - "9990:9990"
    volumes:
      - ./models:/app/models